### ISSUE TITLE
fixed center _start_location

### ISSUE THREAD

**Issue by Gracechung-sw** [Gracechung-sw/rl_apx_detection#2]
### ISSUE
- Group:  `study`, `implementation`, `feedback & fix`
- Type: `bug`, `feature`, `delete` 
- Detail: fix actions from client redux

### TODO
1. [x] 현재는 80%내에서 random하게 _start_location을 잡고 나서 episode시작 이를 고정점으로 하는 것에 대한 논의 및 피드백
2. [ ] center _start_location
3. [ ] appendicitis landmark 의 평균점 (과도하게 쉬워지는 경향이 있을 것 같음)

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
