### ISSUE TITLE
CT image resampling

### ISSUE THREAD

**Issue by Gracechung-sw** [Gracechung-sw/rl_apx_detection#3]
### ISSUE
- Group:  `study`, `implementation`, `feedback & fix`
- Detail: FOV와 spacing resolution의 개념

### TODO
1. [ ] 현재 x, y는 0.6~0.8 사이, z는 3~4 사이 의  spacing resolution
2. [ ] 2mmX2mmX2mm로 resample
3. [ ] 그에 맞게 landmark도 다시 추출
- 기존에 뽑은 landmark에서 그냥 비례하게만 해주기 math.round(Nx1/Nx0)*x0
- 또는 그냥 다시 2x2x2로 resample 한 것에서 새로 다시 뽑기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
